name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Kotlin Linter
      uses: vroy/gha-kotlin-linter@v2
